---
- hosts: all
  tasks:
    - name: add user
      become: yes
      ansible.builtin.user:
        name: ansible-worker
        groups: sudo
        generate_ssh_key: true

    - name: git
      become: yes
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
    
    - name: sshkeys
      become: yes
      ansible.builtin.copy:
        dest: "/home/ansible-worker/.ssh/"
        src: "ssh_keys/"

    - name: clone rep
      become: yes
      ansible.builtin.git:
        repo: https://github.com/iphilka/stud-template
        dest: "/home/ansible-worker/www"

    - name: index.html
      become: yes
      ansible.builtin.copy:
        dest: "/home/ansible-worker/www/index.html"
        src: index.html
        owner: ansible-worker
        group: ansible-worker

    - name: nginx
      become: yes
      ansible.builtin.apt:
        name: nginx
        state: present
   
    - name: conf nginx 
      become: yes
      ansible.builtin.copy:
        dest: "/etc/nginx/sites-available/ansible.iphilka.ru.conf"
        src: ansible.iphilka.ru.conf
        owner: root
        group: root
        mode: 0755
      
    - name: starting
      become: yes
      file:
        src: "/etc/nginx/sites-available/ansible.iphilka.ru.conf"
        dest: "/etc/nginx/sites-enabled/ansible.iphilka.ru.conf"
        state: link
      

    - name: turn off
      become: yes
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      
    - name: nginx reboot
      become: yes
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
